version: '3.9'

services:
  frontend:
    image: react-app:1
    build:
      context: ./docker-react-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: springboot-app:1
    build:
      context: ./docker-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


