version: "3.9"

services:
  frontend:
    image: teja463/docker-react-app:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: teja463/docker-java:latest
    ports:
      - "8080:8080"

